language: java
jdk:
- oraclejdk8
script: gradle test jacocoTestReport sonarqube
env:
  global:
  - secure: LUCrrkDxv6DMh1qSEebbkqEe2N91lw2tv18SCUaWtKCMswgRLUr0uJe5heAR7gcL8kVvvLyNl3LcgXReCThMffs8Ma2e1WMP9Qwn31DAIJIADJC3VXFobO2uyn1iqJTQ7kUei8jYlPN0+IRzrPeHjavDo1ATWqzOU2+Pc5UuorI=
  - TERM=dumb
  - secure: bXBz3zPJRkYzty1pFceq3zHzJZu8/chanRauWCPWQDY0mTMn3+4+PwyeANtN2MFbQibIcLgnC5rHlM9o6ZjQhRpQHivN98T6qQKFrYTyeVDfydmJuOZnbgIobqY79l+QRFPLO5lp4yNOUKrLbEkvyWXbx1ZsOVTnZI4FF3wXQ3U=
cache:
  directories:
  - "$HOME/.m2"
addons:
  coverity_scan:
    project:
      name: grzesuav/gjpf-core
      description: fork of jpf-core
    build_command_prepend: gradle clean
    build_command: gradle classes testClasses
    branch_pattern: coverity-scan
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/ce121f2a865e7ee2c9af
    on_success: change
    on_failure: always
    on_start: never
before_install:
- pip install --user codecov
after_success:
- gradle coveralls
- codecov
